### PR TITLE
Implement Ecto 3 Callbacks

### PR DESCRIPTION
**Pull request by sheharyarn**
Implements Ecto 3 callbacks to get rid of the behaviour implementation warnings.

### CODE REVIEW

**Comment by omh** [comment]
Thanks @sheharyarn, this has been bugging me as well. Was about to put together a PR, but you beat me to it. Hopefully it'll get merged soon.

**Comment by sheharyarn** [comment]
Hey @gpedic, let me know if there's anything else I should do here.

**Comment by gpedic** [comment]
Hey @sheharyarn, might be nice to add the tests, so we can keep the ~100% coverage

**Comment by sheharyarn** [comment]
We're just implementing the required Ecto callbacks with default values. Not sure what the tests will be for this.

**Comment by gpedic** [comment]
> We're just implementing the required Ecto callbacks with default values. Not sure what the tests will be for this.

It doesn't have to be anything sophisticated, these functions will be part of public interface of `Ecto.ShortUUID` so let's just to lock this down with some simple asserts like

assert embed_as(nil) == :self
assert equal?(uuid, uuid) == true
assert equal?(uuid, otheruuid) == false

**Comment by sheharyarn** [comment]
@gpedic updated

**Comment by gpedic** [comment]
I've published v0.1.3 which includes this to Hex.pm

**Pull request merged**
